' The Blank Page item template is documented at https://go.microsoft.com/fwlink/?LinkId=402352&clcid=0x409

''' <summary>
''' The initial page and setup view for the application.
''' </summary>
''' 
''' <remarks>
''' Created by Tommy Crews
''' </remarks>

Public NotInheritable Class MainPage
    Inherits Page

    ' GLOBAL VARIABLES
    Public mainTitleBar = Core.CoreApplication.GetCurrentView().TitleBar
    Public mainTitleBarProperties = ApplicationView.GetForCurrentView().TitleBar

    Private Sub Page_Loaded(sender As Object, e As RoutedEventArgs)
        ' EVENT:Loaded -- Initial page setup upon load completion.

        Me.InitializeComponent()

        ApplicationView.PreferredLaunchViewSize = New Size(400, 800)
        ApplicationView.PreferredLaunchWindowingMode = ApplicationViewWindowingMode.PreferredLaunchViewSize

        ' Setup window for acrylic effects.
        mainTitleBar.ExtendViewIntoTitleBar = True
        mainTitleBarProperties.ButtonBackgroundColor = Windows.UI.Colors.Transparent
    End Sub

    Private Sub PivotItems_Handler(sender As Object, args As RoutedEventArgs)
        ' Enables builderPivot navigation using numbersButton and lettersButton.

        ' Listen for a Click event and call the appropriate builderPivot index.
        If sender Is numbersButton Then
            Debug.WriteLine("INFO: Numbers Button Clicked.")
            numbersButton.IsChecked = True
            lettersButton.IsChecked = False
            builderPivot.SelectedIndex = 0
        ElseIf sender Is lettersButton Then
            Debug.WriteLine("INFO: Letters Button Clicked.")
            lettersButton.IsChecked = True
            numbersButton.IsChecked = False
            builderPivot.SelectedIndex = 1
        End If
    End Sub

    Private Sub NumbersQuantitySlider_Changed(sender As Object, e As RangeBaseValueChangedEventArgs)
        ' Handles a change in value of NumbersQuantitySlider.

        ' I don't know why I need this but it seems necessary for fixing types.
        Dim numbersQuantitySliderSender As Slider = TryCast(sender, Slider)

        ' Display sider value on adjacent numbersQuantitySliderLabel.
        If numbersQuantitySliderSender IsNot Nothing Then
            Try
                numbersQuantitySliderLabel.Text = numbersQuantitySliderSender.Value.ToString()
            Catch exception As Exception
                ' Lots of null exceptions generated by this.
                ' Probably Not the best way to do this.
                Debug.WriteLine("ERROR: " & exception.ToString())
            End Try
        End If
    End Sub

    Private Sub LaunchButtonClicked(sender As Object, e As RoutedEventArgs) Handles LaunchButton.Click
        ' Handles LaunchButton click event.

        Me.Frame.Navigate(GetType(CardViewerWindow))
    End Sub

    Private Sub numbersBlanksQuantitySlider_Changed(sender As Object, e As RangeBaseValueChangedEventArgs)
        ' Handles numbersBlanksQuantitySlider value changes.

        Dim numbersBlanksQuantitySliderSender As Slider = TryCast(sender, Slider)

        ' Display sider value on adjacent numbersBlanksQuantitySliderLabel.
        If numbersBlanksQuantitySliderSender IsNot Nothing Then
            Try
                numbersBlanksQuantitySliderLabel.Text = numbersBlanksQuantitySliderSender.Value.ToString()
            Catch exception As Exception
                ' Lots of null exceptions generated by this.
                ' Probably Not the best way to do this.
                Debug.WriteLine("ERROR: " & exception.ToString())
            End Try
        End If
    End Sub

    Private Sub numbersBlanksPositionButton_Changed(sender As Object, e As RoutedEventArgs)
        ' Handle numbersBlanksPosition[x]Button clicks.

        If sender Is numbersBlanksPositionLeftButton Then
            Debug.WriteLine("INFO: Numbers Left Blanks Position Button Clicked.")
            numbersBlanksPositionLeftButton.IsChecked = True
            numbersBlanksPositionMiddleButton.IsChecked = False
            numbersBlanksPositionRightButton.IsChecked = False
            numbersBlanksPositionRandomButton.IsChecked = False
        ElseIf sender Is numbersBlanksPositionMiddleButton Then
            Debug.WriteLine("INFO: Numbers Middle Blanks Position Button Clicked.")
            numbersBlanksPositionLeftButton.IsChecked = False
            numbersBlanksPositionMiddleButton.IsChecked = True
            numbersBlanksPositionRightButton.IsChecked = False
            numbersBlanksPositionRandomButton.IsChecked = False
        ElseIf sender Is numbersBlanksPositionRightButton Then
            Debug.WriteLine("INFO: Numbers Right Blanks Position Button Clicked.")
            numbersBlanksPositionLeftButton.IsChecked = False
            numbersBlanksPositionMiddleButton.IsChecked = False
            numbersBlanksPositionRightButton.IsChecked = True
            numbersBlanksPositionRandomButton.IsChecked = False
        ElseIf sender Is numbersBlanksPositionRandomButton Then
            Debug.WriteLine("INFO: Numbers Random Blanks Position Button Clicked.")
            numbersBlanksPositionLeftButton.IsChecked = False
            numbersBlanksPositionMiddleButton.IsChecked = False
            numbersBlanksPositionRightButton.IsChecked = False
            numbersBlanksPositionRandomButton.IsChecked = True
        End If
    End Sub
End Class

' S. D. G.